---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/branches/base_job_flags.yml

$inherits:
  from: tasks/branches/base_job_flags.yml

builds:
  linux:
    platforms:
      - Linux
    types:
      debug:
        task: tasks/builds/dbg_linux32.yml
  linux64:
    platforms:
      - Linux64
    types:
      debug:
        task: tasks/builds/dbg_linux64.yml
  linux64-st-an:
    platforms:
      - Linux64 Static Analysis
    types:
      opt:
        task: tasks/builds/opt_linux64_st-an.yml
  macosx64:
    platforms:
      - MacOSX64
    types:
      debug:
        task: tasks/builds/dbg_macosx64.yml
  macosx64-st-an:
    platforms:
      - MacOSX64 Static Analysis
    types:
      opt:
        task: tasks/builds/opt_macosx64_st-an.yml

tests:
  cppunit:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_cppunit.yml
  crashtest:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_crashtest.yml
  crashtest-e10s:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_crashtest_e10s.yml
  firefox-ui-functional:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_firefox_ui_functional.yml
  firefox-ui-functional-e10s:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_firefox_ui_functional_e10s.yml
  gtest:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_gtest.yml
  jittests:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_jittests.yml
  jsreftest:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_jsreftest.yml
  jsreftest-e10s:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_jsreftest_e10s.yml
  marionette:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_marionette.yml
  marionette-e10s:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_marionette_e10s.yml
  mochitest:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_plain.yml
  mochitest-e10s:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_plain_e10s.yml
  mochitest-a11y:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_a11y.yml
  mochitest-browser-chrome:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_bc.yml
  mochitest-browser-chrome-e10s:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_bc_e10s.yml
  mochitest-chrome:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_chrome.yml
  mochitest-devtools-chrome:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_dt.yml
  mochitest-jetpack:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_jetpack.yml
  mochitest-webgl:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_gl.yml
  reftest:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_reftest.yml
  reftest-e10s:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_reftest_e10s.yml
  web-platform-tests:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_web_platform_tests.yml
  web-platform-tests-e10s:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_web_platform_tests_e10s.yml
  web-platform-tests-reftests:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_web_platform_tests_reftests.yml
  web-platform-tests-reftests-e10s:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_web_platform_tests_reftests_e10s.yml
  xpcshell:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_xpcshell.yml

# Miscellaneous tasks.
tasks:
  eslint-gecko:
    task: tasks/tests/eslint-gecko.yml
    root: true
    when:
      file_patterns:
        # Files that are likely audited.
        - '**/*.js'
        - '**/*.jsm'
        - '**/*.jsx'
        - '**/*.html'
        - '**/*.xml'
        # Run when eslint policies change.
        - '**/.eslintignore'
        - '**/*eslintrc*'
        # The plugin implementing custom checks.
        - 'testing/eslint-plugin-mozilla/**'
        # Other misc lint related files.
        - 'tools/lint/**'
